#
# Copyheart Rogdham, 2017
# See http://copyheart.org/ for more details.
#
# This program is free software. It comes without any warranty, to the extent
# permitted by applicable law. You can redistribute it and/or modify it under
# the terms of the CC0 1.0 Universal Licence (French).
# See https://creativecommons.org/publicdomain/zero/1.0/deed.fr for more
# details.
#

hashquine.gif: fastcoll
	./generate.py $@

fastcoll:
	@echo
	@echo 'Download and compile $@ from http://www.win.tue.nl/hashclash/'
	@echo
	@exit 1
